Update to OpenStudio 3.0 and ruby 2.5
BuildingSync/BuildingSync-gem pull request #68
Opened 2020-08-26 14:23 UTC by TMaile

this implements #63

2020-09-14 18:38 UTC, corymosiman12 commented on .travis.yml
> +#  - bundle exec rspec spec/tests/translator_spec.rb // 2 failures, both: expect(File.exist?(sql_file)).to be true got false
Can we get this passing before merging?  Is there a reason why this should not be passing?

2020-09-14 18:47 UTC, corymosiman12 requested changes
All looks good, just want to re-review after #70 gets merged into `DA_Update`, as I think that will take care of some additional things.

2020-09-22 04:16 UTC, corymosiman12 commented on .travis.yml
> +#  - bundle exec rspec spec/tests/translator_spec.rb // 2 failures, both: expect(File.exist?(sql_file)).to be true got false
resolved via  https://github.com/BuildingSync/BuildingSync-gem/pull/68/commits/51b05f16e2979608caf8bc151edd7f91bce6c404

2020-09-22 04:17 UTC, corymosiman12 approved these changes
looks good

2020-09-22 21:19 UTC, TMaile commented
this is done now, but is waiting for https://github.com/BuildingSync/BuildingSync-gem/pull/70 to get done and merged

2020-09-24 12:52 UTC, merged